export const FETCH_UNIDADES_MEDIDA = "FETCH_UNIDADES_MEDIDA";
export const FETCH_CLASIFICADORES = "FETCH_CLASIFICADORES";
export const FETCH_IVA = "FETCH_IVA";
export const FETCH_RETEFUENTE = "FETCH_RETEFUENTE";
export const FETCH_TIPO_ADQUIRIDO = "FETCH_TIPO_ADQUIRIDO";

export const POST_NEW_ARTICLE = "POST_NEW_ARTICLE";